### ISSUE TITLE
cache.clear() doesn't call the callback

### ISSUE THREAD

**Issue by pjsg** [jlhutch/pylru#23]
It appears that calling cache.clear() doesn't call the eviction callback... Is this by design or an accident?

**Comment by jlhutch** [comment]
Design.

The cache.clear() method can simply blow the cache away (current behavior) or it can evict each entry calling the callback function, if there is one. It is not obvious, at least to me, that either behavior is clearly more intuitive.

At a practical level, the WriteBackCacheManager class gives an example of the tradeoffs that motivated the API's design.

The clear() method there needs to clear the cache and the backing storage. Since the storage is being cleared anyway, we don't want the callbacks executing, we really want to blow the cache away.

In the sync() method we need to write back the dirty cache entries. If cache.clear() did called the callbacks, it would make this simpler. However, the performance would not be as good, because every entry in the cache would have its callback executed so that it could be looked up in the dirty set. For many cases, it is faster to just walk the dirty set directly, sync those, then blow the cache away.
