### ISSUE TITLE
Feature: Allow caching of none hashable types by using id(object) as key

### ISSUE THREAD

**Issue by daliclass** [jlhutch/pylru#29]
Hello!

I am working with a lot of large numpy.ndarray and posting them over a network. I want to use a LRU cache so that if I make a call with the same numpy.ndarray I will get the same answer. numpy.ndarray take up a lot of memory and are unhashable, so I would need to use ```id(object)``` to identfiy the images.

I would be happy to do the work to enable some kind of ```id(object)``` mode (or md5 etc) for caching if the feature would be accepted. This is very relevant to my use cases and I imagine would help other people working with large unhashable objects.

To be clear this is talking about using @lrudecorator(100, mode=id) or something like that to support caching of large unhashable objects. I can use the current library by interacting with the cache directly to solve my problem but would like to make it even simpler in the future. If above in unclear I will be providing code snippets later on to give more detail to my feature idea.

Let me know what you think

**Comment by jlhutch** [comment]
I apologize if I misunderstand your proposal, but I think it is probably a bad idea to use id(object) as the key in a cache. According to the Python documentation, "Two objects with non-overlapping lifetimes may have the same id() value." You could conceivably call cache[id(a)] = value, later call cache[id(b)] and retrieve the value for 'a' even when a != b. Almost certainly not what most people want.

**Comment by daliclass** [comment]
It could be to specific let me try and explain with a example of what my use case has been to see if we think it could be helpful. If not happy to drop it.

```
class CachingSomething():

    def __init__(self, model_services: ModelApi):
        self.model_api: ModelApi = model_services
        self.model_cache: lrucache = lrucache(size=10)

    def get_prediction(self, image: ndarray) -> dict:
        image_key = self.__get_key(image)
        cached_prediction = self.model_cache.get(self.__get_key(image))

        if not cached_prediction == None:
            return cached_prediction

        new_prediction = self.model_api.get_prediction(image)
        self.model_cache[image_key] = new_prediction
        return new_prediction

    @staticmethod
    def __get_key(image) -> int:
        """
          benchmarks over 1000 images
          md5 took 37 seconds
          id took ~0.00003
        """
        return id(image)
```

id is a bit flakey I agree, but is unique enough for my use case and I am happy to trade the exactness for speed (my ndarrays are in memory for there entire lifetime). However md5 might be useful for people who care about the exactness.

The api I could see being nice would be something like this

```
class CachingSomething():

    def __init__(self, model_services: ModelApi):
        self.model_api: ModelApi = model_services

    @lrucache(10, strategy_better_name_required=md5)
    def get_prediction(self, image: ndarray) -> dict:
        self.model_api.prediction(image)
```

**Comment by jlhutch** [comment]
Thank you, I understand now. I am not interested in adding that functionality to pylru at this time.

The fact that an object's id is not unique for objects with non-overlapping lifetimes makes me uneasy. For your use case, where you are guaranteeing the lifetime of the objects, it works. But, in general, it could lead to code that is incorrect in subtle and difficult to debug ways, all because the user violated an implicit requirement about object lifetimes. Even if we documented the behavior, I think that is a pretty big gotcha.

I also admit a strong bias toward keeping both the code and API for pylru simple (maybe to a fault). So anything that changes the API has a pretty high bar to clear, especially if it can be accomplished otherwise.

Your idea of using an md5 hash, or something similar, to generate an effectively unique key is interesting. I'm not sure how that would work. If objects expose a way to generate their md5 hash, it seems like we're kind of back to objects being hashable. Maybe I'm missing something.

That said, I think you are right that others would find a more convenient way to do something like this useful. Maybe a custom function decorator that passed the object id to pylru? Perhaps you would consider sharing that code separately?

**Comment by daliclass** [comment]
So an object would not need to know how to generate its own md5 hash we could do that with the global md5 function. Another cool thing of using a hash like a md5 is it is much smaller than the object size. 

When working with images in memory its not uncommon for them to be around 1mb+ and the way pyrlu currently works is to keep a copy of the argument to the function in memory as part of they key if you had a many images you could quite easily get OOM errors. This would apply to other large objects.

I think a external decorator is a good call, I can't fully see how it will work but will happily figure that out. We can then reopen the conversation if and when it see's any use.

Thanks for the discussion and your work on pyrlu 👍
